In [2]:
library(R2DAG)
library(pcalg)
library(tictoc)

In [3]:
A0 <- matrix(c(1, 0, -2, 
                -2, 1, 0,  
                0, -2, 1), nrow = 3, byrow = TRUE)

data <- gen_svar(1000, A0=A0, list_A=list(), df=20)

In [10]:
# Function to group matrices by their frequency and sort by decreasing frequency
group_matrices_by_frequency <- function(mat_list) {
  # Convert each matrix to a comparable string
  matrix_strings <- sapply(mat_list, function(m) paste(c(m), collapse = ","))
  
  # Find unique matrices and their frequencies
  unique_strings <- unique(matrix_strings)
  frequencies <- table(matrix_strings)
  
  # Initialize temporary list
  temp_list <- list()
  
  # Fill the temporary list
  for (us in unique_strings) {
    freq <- as.character(frequencies[us])
    
    # Create the frequency group if it doesn't exist
    if (!freq %in% names(temp_list)) {
      temp_list[[freq]] <- list()
    }
    
    # Add the actual matrix to the correct group
    matrix_index <- match(us, matrix_strings)  # find one index where it appears
    temp_list[[freq]] <- append(temp_list[[freq]], list(mat_list[[matrix_index]]))
  }
  
  # Step: Sort the list by numeric frequency decreasing
  freq_order <- sort(as.numeric(names(temp_list)), decreasing = TRUE)
  output_list <- temp_list[as.character(freq_order)]
  
  return(output_list)
}


In [9]:
mat_list <- list()
for (i in 1:100){
    data <- gen_svar(1000, A0=A0, list_A=list(), df=20)
    mat_list[[i]] <- data2amat(data)$amat
    }

In [11]:
group_matrices_by_frequency(mat_list)

$`34`
$`34`[[1]]
     [,1] [,2] [,3]
[1,]    0    1    1
[2,]    0    0    1
[3,]    0    0    0


$`24`
$`24`[[1]]
     [,1] [,2] [,3]
[1,]    0    1    0
[2,]    0    0    0
[3,]    1    1    0


$`20`
$`20`[[1]]
     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    1    0    1
[3,]    1    0    0


$`12`
$`12`[[1]]
     [,1] [,2] [,3]
[1,]    0    0    1
[2,]    1    0    1
[3,]    0    0    0


$`7`
$`7`[[1]]
     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    1    0    0
[3,]    1    1    0


$`3`
$`3`[[1]]
     [,1] [,2] [,3]
[1,]    0    1    1
[2,]    0    0    0
[3,]    0    1    0